poem/poem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('poem_app.urls')),
]

poem/poem_app/urls.py
from django.urls import path
from . import views

app_name = 'poem'

urlpatterns = [
    path('', views.PoemList.as_view(), name='list'),
    path('<slug:slug>/', views.PoemDetail.as_view(), name='detail'),
    path('poem/create/', views.PoemCreate.as_view(), name='create'),
    path('<slug:slug>/update/', views.PoemUpdate.as_view(), name='update'),
    path('<slug:slug>/delete', views.PoemDelete.as_view(), name='delete'),
]

poem/poem_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Poem(models.Model):
    title = models.CharField(max_length=50)
    poet = models.CharField(max_length=50)
    slug = models.SlugField(max_length=63)
    poem = models.TextField()

    class Meta:
        unique_together=(('title','poet'),)
        ordering = ['title']

    def get_absolute_url(self):
        return reverse('poem:detail', kwargs={'slug':self.slug})

    def get_delete_url(self):
        return reverse('poem:delete', kwargs={'slug':self.slug})

    def get_update_url(self):
        return reverse('poem:update', kwargs={'slug':self.slug})

poem/poem_app/forms.py
from django import forms
from .models import Poem
from django.utils.text import slugify

class PoemForm(forms.ModelForm):
    class Meta:
        model=Poem
        #experiment with exclude=['slug'] 
        exclude = ['slug'] 

    def save(self):
        instance = super().save(commit=False)
        instance.slug = slugify(instance.title)+ '-' + slugify(instance.poet)
        instance.save()
        return instance

poem/poem_app/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import View
from django.shortcuts import get_object_or_404, HttpResponseRedirect
from .models import Poem
from .forms import PoemForm
# Create your views here.

class PoemList(View):
    model = Poem
    template_name = 'poem_app/poem_list.html'

    def get(self, request):
        poem_list = self.model.objects.all()
        return render(
            request,
            self.template_name,
            {'poems':poem_list}
        )

class PoemDetail(View):
    model = Poem
    template_name = 'poem_app/poem_detail.html'

    def get(self, request, slug):
        poem = get_object_or_404(self.model, slug__iexact=slug)
        return render(
            request,
            self.template_name,
            {'poem':poem}
        )

class PoemCreate(View):
    template_name = "poem_app/poem_create.html"
    form_class = PoemForm

    def get(self, request):
        return render(
            request,
            self.template_name,
            {'form':self.form_class()}
        )

    def post(self, request):
        bound_form = self.form_class(request.POST)
        if bound_form.is_valid():
            new_poem = bound_form.save()
            return redirect(new_poem)
        else:
            return render(
                request,
                self.template_name,
                {'form':bound_form}
            )

class PoemDelete(View):
    model = Poem
    template_name = 'poem_app/poem_delete.html'
    success_url = reverse_lazy('poem:list')

    def get(self, request, slug):
        poem = get_object_or_404(self.model, slug__iexact=slug)
        context = {'poem':poem}
        return render(
            request,
            self.template_name,
            context
        )
    
    def post(self, request, slug):
        poem = get_object_or_404(self.model, slug__iexact=slug)
        poem.delete()
        return HttpResponseRedirect(self.success_url)

class PoemUpdate(View):
    model = Poem
    template_name = 'poem_app/poem_update.html'
    form_class = PoemForm

    def get(self, request, slug):
        poem = get_object_or_404(self.model, slug__iexact=slug)
        return render(
            request,
            self.template_name,
            {'form':self.form_class(instance=poem),
             'poem':poem}
        )

    def post(self, request, slug):
        poem = get_object_or_404(self.model, slug__iexact=slug)
        bound_form = self.form_class(request.POST, instance=poem)
        if bound_form.is_valid():
            update_poem = bound_form.save()
            return redirect(update_poem)
        else:
            return render(
                request,
                self.template_name,
                {'form':bound_form,
                 'poem':poem}
            )

poem/poem_app/templates/poem_app/base_poem.html
{% extends "base.html" %}
{% block title %}
Poem
{% endblock title %}

{% block content %}
<div class="container">

</div>
{% endblock content %}

poem/poem_app/templates/poem_app/poem_create.html
{% extends "poem_app/base_poem.html" %}
{% block title %}
{{ block.super }} - Create
{% endblock title %}
{% block content %}
<div class="container">
    <form action="{% url 'poem:create' %}" method="post">
        {% csrf_token %} {{form.as_p}}
        <button class="btn btn-primary" type="submit">Submit</button>
    </form>
</div>
{% endblock content %}

poem/poem_app/templates/poem_app/poem_delete.html
{% extends "poem_app/base_poem.html" %}
{% block title %}
{{ block.super }} - Delete
{% endblock title %}

{% block content %}
<form action="{{poem.get_delete_url}}" method="POST">
    {% csrf_token %}
    <p>Are you sure you want to delete {{poem.title}} by {{poem.poet}} </p>
    <button class="btn btn-warning" type="submit">Yes</button>
    <button class="btn btn-default" type="button"><a href="{{poem.get_absolute_url}}">No</a></button>
</form>
{% endblock content %}

poem/poem_app/templates/poem_app/poem_detail.html
{% extends "poem_app/base_poem.html" %} 
{% block title %} 
{{ block.super }} - {{poem.title}} 
{% endblock title %}

{% block content %}
<div class="container">
    <h1>{{poem.title}}</h1>
    <h3>by {{poem.poet}}</h3>
    <br>
    <br>
    <h2>
        {{poem.poem|linebreaks}}
    </h2>   
    <button type="button" class="btn btn-warning"><a href="{{poem.get_delete_url}}">Delete Poem</a></button>
    <button type="button" class="btn btn-primary"><a href="{{poem.get_update_url}}">Update Poem</a></button>
</div>
{% endblock content %}

poem/poem_app/templates/poem_app/poem_list.html
{% extends "poem_app/base_poem.html" %}
{% block title %}
{{ block.super }} - List
{% endblock title %}

{% block content %}
<div class="jumbotron">
    <h1>List of poems available</h1>
    <ul>
        {% for poem in poems %}
        <li><a href="{{poem.get_absolute_url}}">{{poem.title}} by {{poem.poet}}</a></li>
        {% empty %}
        <li><em>No Poem available</em></li>
        {% endfor %}
    </ul>
</div>
{% endblock content %}

poem/poem_app/templates/poem_app/poem_update.html
{% extends "poem_app/base_poem.html" %}
{% block title %}
{{ block.super }} - Update Poem
{% endblock title %}
{% block content %}
<form action="{{poem.get_update_url}}" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button class="btn btn-primary" type="submit">Update Poem</button>
</form>
{% endblock content %}

poem/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}
    Base Template
    {% endblock title %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
        crossorigin="anonymous">
</head>
<body>
    
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'poem:list' %}">Poem</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'poem:create' %}">Create <span class="sr-only">(current)</span></a>
      </li>
    </ul>
  </div>
</nav>
    
    <div class="container">
         {% block content %} {% endblock content %}
    </div>

    <!-- Javascripts -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>
</html>